log_level = "debug"
# port = 3000
mnemonic = "equal dragon fabric refuse stable cherry smoke allow alley easy never medal attend together lumber movie what sad siege weather matrix buffalo state shoot"

default_relay = "ws://localhost:7010"